version: "3.8"

services:
    postgres:
        image: postgres:alpine
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
        restart: on-failure:3

    redis:
        image: redis
        ports:
            - 6379:6379
