version: "3.8"

services:
    postgres:
        image: postgres:alpine
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: postgres
        ports:
            - 5432:5432
        restart: on-failure:3

    redis:
        image: redis
        ports:
            - 6379:6379

    sftp:
        image: atmoz/sftp
        volumes:
            - ./product_images:/home/admin/product_images
        ports:
            - "2222:22"
        command: admin:root:1001

    mongo:
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: mongo
        ports:
            - 27017:27017
        restart: on-failure:3

    kafka:
        image: wurstmeister/kafka
        ports:
            - "9092:9092"
        environment:
            KAFKA_LISTENERS: PLAINTEXT://:9092
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - zookeeper
        restart: on-failure:3

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        restart: on-failure:3
